name: phpcs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PHP Code Style Fixer (php-cs-fixer)
      
      - uses: StephaneBour/actions-php-cs-fixer@8.0-bdossantos
        with:
          # Folder to check code style
          dir: src/
